[workspace]
members = ["crates/*"]
exclude = ["ide/src/tests/mock_project"]
resolver = "2"

[workspace.dependencies]
rustc_plugin = "=0.15.0-nightly-2026-05-01"
rustc_utils = {version = "=0.15.0-nightly-2026-05-01", features = ["indexical"]}
indexical = {version = "0.9.3", default-features = false, features = ["rustc"]}

[profile.bench]
debug = true