[config]
skip_core_tasks = true
default_to_workspace = false

[tasks.watch-cargo]
script = "cargo watch -x 'install --path crates/flowistry_ide --debug --offline'"
install_crate = { crate_name = "cargo-watch" }

[tasks.watch-js]
script = "cd ide && npm run watch"

[tasks.watch.run_task]
name = ["watch-cargo", "watch-js"]
parallel = true
