git clone https://github.com/SergioBenitez/Rocket
git clone https://github.com/diesel-rs/diesel
git clone https://github.com/hyperium/hyper
git clone https://github.com/image-rs/image
git clone https://github.com/dimforge/nalgebra
git clone https://github.com/xiph/rav1e
git clone https://github.com/rayon-rs/rayon/
git clone https://github.com/mrDIMAS/rg3d
git clone https://github.com/ctz/rustls
git clone https://github.com/mozilla/sccache
